apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # This is for demonstration only. In a real deployment, this would be managed by Vault
  # The value is base64 encoded "This is a secret managed by Kubernetes"
  secret-message: VGhpcyBpcyBhIHNlY3JldCBtYW5hZ2VkIGJ5IEt1YmVybmV0ZXM=